---
platforms:
  - name: ansible-role-pmm-client-ubuntu-2404
    image: ubuntu:24.04
    command: /lib/systemd/systemd
    tmpfs:
      - /run
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /var/run/docker.sock:/var/run/docker.sock
    cgroupns_mode: host
    network_mode: host
