---
- name: Prepare
  hosts: all
  tasks:
    - name: Install Docker
      ansible.builtin.include_role:
        name: boutetnico.docker

    - name: Create a MySQL test container
      community.general.docker_container:
        env:
          MYSQL_ROOT_PASSWORD: root
        image: percona:latest
        name: pmm-mysql
        ports:
          - "3306:3306"
        state: started

    - name: Create a MongoDB test container
      community.general.docker_container:
        image: mongo:latest
        name: pmm-mongo
        ports:
          - "27017:27017"
        state: started

    - name: Setup PMM server
      ansible.builtin.include_role:
        name: boutetnico.pmm_server
